config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

    resources :users
    resources :weapons
    resources :enemies, only: [:update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enemy.rb
class Enemy < ApplicationRecord
    enum kind: [ :goblin, :orc, :demon, :dragon ]
    validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }
    validates_presence_of :name, :power_base, :power_step, :level, :kind

    def current_power
        power_base + ((level - 1) * power_step)
    end
end

app/models/user.rb
class User < ApplicationRecord
    enum kind: [ :knight, :wizard ]
    
    validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }    

    def title 
        "#{self.kind} #{self.nickname} ##{self.level}"
    end
end

app/models/weapon.rb
class Weapon < ApplicationRecord

    validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }    

    def current_power
        (self.powerbase + ((self.level - 1) * self.powerstep))
    end

    def title
        "#{self.name} ##{self.level}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController

  before_action :set_enemy

  def update
    if @enemy.update(enemy_params)
      render json: @enemy, status: :ok
    else
      render json: { errors: @enemy.errors }, status: :unprocessable_entily
    end
  end

  def destroy
    @enemy.destroy
    head 204
  end

  private

  def enemy_params
    params.permit(:name, :power_base, :power_step, :level, :kind)
  end

  def set_enemy
    @enemy = Enemy.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    render json: { message: e.message }, status: :not_found
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :kind, :level)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def create
    @weapon = Weapon.create(weapon_params)
    redirect_to weapons_path
  end

  def show
    @weapon = Weapon.find(params[:id])
  end

  def delete
    @weapon = Weapon.find(params[:id])
    begin
      @weapon.destroy
    rescue => erro
      logger.debug "#{@weapon.nome}: #{erro}"
    end
  end

  private

  def weapon_params
    params.require(:weapon).permit(:name, :description, :powerbase, :powerstep, :level, :currentpower, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/enemies/destroy.html.erb
<h1>Enemies#destroy</h1>
<p>Find me in app/views/enemies/destroy.html.erb</p>

app/views/enemies/update.html.erb
<h1>Enemies#update</h1>
<p>Find me in app/views/enemies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLikeAHero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<% @users.each do |user| %>
    <p> <%= user.title %> </p>
<% end %>

app/views/weapons/create.html.erb
<h1>Weapons#create</h1>
<p>Find me in app/views/weapons/create.html.erb</p>

app/views/weapons/delete.html.erb
<h1>Weapons#delete</h1>
<p>Find me in app/views/weapons/delete.html.erb</p>

app/views/weapons/index.html.erb
<% @weapons.each do |weapon|%>
    <p> <%= weapon.name %> </p>
    <p> <%= weapon.currentpower.to_s %> </p>
    <p> <%= weapon.title %> </p>
    <p> <%= link_to 'Detalhes', weapon_path(weapon.id)  %> </p>
<% end %>

app/views/weapons/show.html.erb
<h1>Weapons#show</h1>
<p><%= @weapon.name %></p>
<p><%= @weapon.description %></p>
<p><%= @weapon.powerbase %></p>
<p><%= @weapon.powerstep %></p>
<p><%= @weapon.level %></p>
<p><%= @weapon.currentpower %></p>
<p><%= @weapon.title %></p>